// Curated verbal bank: word relations (D) and sentence completion (E).
// RULE: an item reaches the child only when approved is true. In the prototype, config.showDraftVerbal
// lets the parent see drafts inside a mission in order to judge them. All text is without nikud.
// Option 0 is always the correct one here; the app shuffles options when serving.

export const VERBAL_BANK = [
  // ---------- D. word relations ----------
  { id: 'rel-001', category: 'relations', subtype: 'worker-material', difficulty: 1, approved: true,
    pair: 'נגר : עץ',
    options: [['חייט : בד', null], ['חייט : מחט', 'same-topic-wrong-relation'], ['אופה : מאפייה', 'association-only'], ['צייר : תמונה', 'same-topic-wrong-relation']],
    explain: 'נגר עובד עם עץ, כמו שחייט עובד עם בד. מחט היא הכלי של החייט, לא החומר שלו.' },
  { id: 'rel-002', category: 'relations', subtype: 'part-whole', difficulty: 1, approved: true,
    pair: 'אצבע : יד',
    options: [['דף : ספר', null], ['יד : אצבע', 'reversed-order'], ['כובע : ראש', 'association-only'], ['מורה : תלמיד', 'association-only']],
    explain: 'אצבע היא חלק מהיד, כמו שדף הוא חלק מהספר. שימו לב לסדר: קודם החלק ואחר כך השלם.' },
  { id: 'rel-003', category: 'relations', subtype: 'tool-function', difficulty: 1, approved: true,
    pair: 'מספריים : לגזור',
    options: [['עיפרון : לכתוב', null], ['נייר : לגזור', 'same-topic-wrong-relation'], ['מחק : עיפרון', 'association-only'], ['ספר : סופר', 'association-only']],
    explain: 'במספריים משתמשים כדי לגזור, כמו שבעיפרון משתמשים כדי לכתוב.' },
  { id: 'rel-004', category: 'relations', subtype: 'opposite', difficulty: 2, approved: true,
    pair: 'חם : קר',
    options: [['גבוה : נמוך', null], ['חם : רותח', 'degree-not-opposite'], ['קר : חורף', 'association-only'], ['גדול : ענק', 'degree-not-opposite']],
    explain: 'חם וקר הם הפכים, כמו גבוה ונמוך. גדול וענק הם לא הפכים, ענק הוא פשוט גדול מאוד.' },
  { id: 'rel-005', category: 'relations', subtype: 'young-adult', difficulty: 2, approved: true,
    pair: 'גור : כלב',
    options: [['טלה : כבשה', null], ['חתול : כלב', 'same-topic-wrong-relation'], ['כלב : נביחה', 'association-only'], ['כלב : גור', 'reversed-order']],
    explain: 'גור הוא כלב צעיר, כמו שטלה הוא כבשה צעירה. שימו לב לסדר: קודם הצעיר ואחר כך הבוגר.' },
  { id: 'rel-006', category: 'relations', subtype: 'cause-effect', difficulty: 2, approved: true,
    pair: 'גשם : שלולית',
    options: [['אש : עשן', null], ['מטרייה : גשם', 'same-topic-wrong-relation'], ['ענן : שמיים', 'association-only'], ['שלולית : מגפיים', 'same-topic-wrong-relation']],
    explain: 'גשם גורם לשלולית, כמו שאש גורמת לעשן. הראשון גורם לשני.' },
  { id: 'rel-007', category: 'relations', subtype: 'animal-action', difficulty: 2, approved: true,
    pair: 'דג : לשחות',
    options: [['ציפור : לעוף', null], ['ציפור : לצייץ', 'same-topic-wrong-relation'], ['דג : ים', 'association-only'], ['סירה : לשחות', 'same-topic-wrong-relation']],
    explain: 'דג זז ממקום למקום בשחייה, כמו שציפור זזה ממקום למקום בתעופה. לצייץ זה משהו שציפור עושה, אבל לא הדרך שבה היא זזה.' },

  // Harder relations, difficulty 3
  { id: 'rel-008', category: 'relations', subtype: 'worker-workplace', difficulty: 3, approved: true,
    pair: 'רופא : מרפאה',
    options: [['ספרן : ספרייה', null], ['ספר : ספרייה', 'same-topic-wrong-relation'], ['רופא : חולה', 'association-only'], ['ספרייה : ספרן', 'reversed-order']],
    explain: 'רופא עובד במרפאה, כמו שספרן עובד בספרייה. ספר נמצא בספרייה אבל לא עובד בה, ובזוג האחרון הסדר הפוך.' },
  { id: 'rel-009', category: 'relations', subtype: 'degree', difficulty: 3, approved: true,
    pair: 'טפטוף : מבול',
    options: [['לחישה : צעקה', null], ['צעקה : לחישה', 'reversed-order'], ['גשם : מטרייה', 'association-only'], ['לחישה : סוד', 'association-only']],
    explain: 'טפטוף הוא גשם חלש מאוד ומבול הוא גשם חזק מאוד. באותו אופן, לחישה היא דיבור חלש וצעקה היא דיבור חזק. שימו לב לסדר: קודם החלש ואחר כך החזק.' },
  { id: 'rel-010', category: 'relations', subtype: 'state-remedy', difficulty: 3, approved: true,
    pair: 'רעב : לאכול',
    options: [['עייף : לישון', null], ['לאכול : רעב', 'reversed-order'], ['רעב : שבע', 'same-topic-wrong-relation'], ['צמא : מים', 'same-topic-wrong-relation']],
    explain: 'מי שרעב צריך לאכול, ומי שעייף צריך לישון. "צמא : מים" קרוב, אבל מים הם דבר ולא פעולה. הפעולה המתאימה היא "לשתות".' },
  { id: 'rel-011', category: 'relations', subtype: 'member-group', difficulty: 3, approved: true, vocabulary: ['נחיל'],
    pair: 'ציפור : להקה',
    options: [['דבורה : נחיל', null], ['ציפור : קן', 'association-only'], ['להקה : ציפור', 'reversed-order'], ['דבורה : דבש', 'association-only']],
    explain: 'להקה היא קבוצה של ציפורים, ונחיל הוא קבוצה של דבורים. גם בלי להכיר את המילה "נחיל" אפשר להגיע לתשובה: בשאר הזוגות הקשר אחר או שהסדר הפוך.' },
  { id: 'rel-012', category: 'relations', subtype: 'tool-operates', difficulty: 3, approved: true,
    pair: 'מפתח : מנעול',
    options: [['שלט : טלוויזיה', null], ['דלת : מנעול', 'same-topic-wrong-relation'], ['מנעול : מפתח', 'reversed-order'], ['מפתח : כיס', 'association-only']],
    explain: 'במפתח מפעילים את המנעול, כמו שבשלט מפעילים את הטלוויזיה.' },

  // ---------- E. sentence completion ----------
  { id: 'sen-001', category: 'sentences', subtype: 'contrast-connector', difficulty: 1, approved: true,
    sentence: 'למרות שירד גשם חזק, הילדים ____ לשחק בחצר.',
    options: [['המשיכו', null], ['הפסיקו', 'ignores-connector'], ['שכחו', 'ignores-connector'], ['פחדו', 'ignores-connector']],
    explain: 'המילה "למרות" אומרת שקרה משהו מפתיע. ירד גשם, ובכל זאת הילדים המשיכו לשחק.' },
  { id: 'sen-002', category: 'sentences', subtype: 'cause', difficulty: 1, approved: true,
    sentence: 'דנה הייתה כל כך ____ , שהיא נרדמה באמצע הסרט.',
    options: [['עייפה', null], ['שמחה', 'ignores-connector'], ['רעבה', 'ignores-connector'], ['סקרנית', 'ignores-connector']],
    explain: '"כל כך... ש" מסביר סיבה ותוצאה. מי שנרדם באמצע סרט היה כנראה עייף מאוד.' },
  { id: 'sen-003', category: 'sentences', subtype: 'double-blank', difficulty: 2, approved: true,
    sentence: 'יואב ____ את המפתח בכל הבית, אבל בסוף ____ אותו בכיס שלו.',
    options: [['חיפש / מצא', null], ['חיפש / איבד', 'half-fits'], ['מצא / חיפש', 'half-fits'], ['שכח / זרק', 'ignores-connector']],
    explain: 'קוראים את כל המשפט: יואב עשה משהו עם המפתח "בכל הבית", ובסוף המפתח היה בכיס שלו. מה שעושים בכל הבית זה לחפש, ומי שהמפתח אצלו בכיס, מצא אותו. שתי המילים צריכות להתאים, וגם הסדר: קודם מחפשים ואחר כך מוצאים.' },
  { id: 'sen-004', category: 'sentences', subtype: 'double-blank', difficulty: 2, approved: true,
    sentence: 'המורה ביקשה שנדבר ____ , כדי לא ____ לתלמידים שנבחנים בכיתה הסמוכה.',
    options: [['בשקט / להפריע', null], ['בקול / להפריע', 'half-fits'], ['בשקט / לעזור', 'half-fits'], ['מהר / להקשיב', 'ignores-connector']],
    explain: 'מדברים בשקט כדי לא להפריע. שתי המילים צריכות להתאים למשפט, לא רק אחת.' },
  { id: 'sen-005', category: 'sentences', subtype: 'inference-vocabulary', difficulty: 3, approved: true, vocabulary: ['מפרכת'],
    sentence: 'הדרך להר הייתה ארוכה ו____ , ולכן עצרנו לנוח כמה פעמים.',
    options: [['מפרכת', null], ['קצרה', 'ignores-connector'], ['נעימה', 'unknown-word-avoided'], ['מהירה', 'ignores-connector']],
    explain: '"מפרכת" פירושה מעייפת מאוד. גם בלי להכיר את המילה אפשר להבין: אם עצרו לנוח כמה פעמים, הדרך הייתה קשה ומעייפת.' },
  { id: 'sen-006', category: 'sentences', subtype: 'condition', difficulty: 2, approved: true,
    sentence: 'אם לא ____ את הצמחים, הם ____ .',
    options: [['נשקה / יתייבשו', null], ['נשקה / יגדלו', 'half-fits'], ['נצייר / יתייבשו', 'half-fits'], ['נקנה / ישמחו', 'ignores-connector']],
    explain: 'צמחים צריכים מים. אם לא משקים אותם, הם מתייבשים. המילה "אם" מחברת בין מה שעושים לבין מה שיקרה.' },

  // Difficulty 3: the register of the official Grade 3 examples (Machon Karni 2022): two blanks, connectors, higher vocabulary.
  { id: 'sen-007', category: 'sentences', subtype: 'concession-connector', difficulty: 3, approved: true,
    sentence: '____ שהתאמן כל יום, יונתן לא ____ לנבחרת בית הספר.',
    options: [['אף על פי / התקבל', null], ['מכיוון / התקבל', 'ignores-connector'], ['אף על פי / התנגד', 'half-fits'], ['כדי / הצטרף', 'ignores-connector']],
    explain: '"אף על פי ש" מודיע שהתוצאה מפתיעה: הוא התאמן כל יום, ובכל זאת לא התקבל. "מכיוון ש" היה מתאים רק אם האימונים היו הסיבה לכך שלא התקבל, וזה לא הגיוני.' },
  { id: 'sen-008', category: 'sentences', subtype: 'cause-connector', difficulty: 3, approved: true, vocabulary: ['ערנות'],
    sentence: 'בזכות ה____ של השכנים, השרפה ____ לפני שגרמה נזק.',
    options: [['ערנות / כובתה', null], ['אדישות / כובתה', 'half-fits'], ['ערנות / התפשטה', 'half-fits'], ['רשלנות / התלקחה', 'ignores-connector']],
    explain: '"בזכות" מציין סיבה טובה לתוצאה טובה. ערנות פירושה שהשכנים שמו לב מהר, ולכן השרפה כובתה בזמן.' },
  { id: 'sen-009', category: 'sentences', subtype: 'result-connector', difficulty: 3, approved: true, vocabulary: ['מפרך'],
    sentence: 'המדריך הסביר שהמסלול ____ , ולכן ביקש מכל המטיילים להצטייד ב____ מים.',
    options: [['מפרך / הרבה', null], ['קצר / הרבה', 'half-fits'], ['מפרך / מעט', 'half-fits'], ['נוח / הרבה', 'ignores-connector']],
    explain: '"ולכן" מחבר סיבה לתוצאה. מסלול מפרך הוא מסלול קשה ומעייף, ולכן צריך הרבה מים.' },
  { id: 'sen-010', category: 'sentences', subtype: 'concession-connector', difficulty: 3, approved: true, vocabulary: ['שככה'],
    sentence: 'אמנם הסופה ____ , אך הרחובות עדיין ____ .',
    options: [['שככה / מוצפים', null], ['התגברה / מוצפים', 'ignores-connector'], ['שככה / יבשים', 'ignores-connector'], ['הבריאה / יבשים', 'ignores-connector']],
    explain: 'במשפט הזה "אמנם... אך" מודה בדבר אחד ומיד מציב מולו דבר שמנוגד לו. "שככה" פירושו נרגעה. הסופה כבר נרגעה, ומול זה עומדת העובדה שהרחובות עדיין מוצפים. בשאר התשובות שני החלקים לא מנוגדים זה לזה, או שהם לא הגיוניים ביחד.' },
  { id: 'sen-011', category: 'sentences', subtype: 'cause-connector', difficulty: 3, approved: true, vocabulary: ['מרתק'],
    sentence: 'מאחר שהספר היה כה ____ , דנה לא הצליחה ____ ממנו עד שעת לילה מאוחרת.',
    options: [['מרתק / להתנתק', null], ['משעמם / להתנתק', 'half-fits'], ['מרתק / ליהנות', 'half-fits'], ['ארוך / לקרוא', 'ignores-connector']],
    explain: '"מאחר ש" פירושו "בגלל ש". ספר מרתק הוא ספר שקשה להפסיק לקרוא, ולכן דנה לא הצליחה להתנתק ממנו.' },
  { id: 'sen-012', category: 'sentences', subtype: 'condition-connector', difficulty: 3, approved: true,
    sentence: 'פירות טריים ____ מהר, ____ שומרים אותם במקרר.',
    options: [['מתקלקלים / אלא אם כן', null], ['מתקלקלים / מפני ש', 'half-fits'], ['נשמרים / אלא אם כן', 'half-fits'], ['מתרבים / אלא אם כן', 'half-fits']],
    explain: 'קוראים את המשפט עם כל תשובה. פירות מתקלקלים מהר, והמקרר הוא מה שמונע את זה, ולכן מתאים "אלא אם כן", שפירושו כאן "חוץ מהמקרה שבו". "מפני ש" היה הופך את המקרר לסיבת הקלקול, ופירות לא "נשמרים מהר" ולא "מתרבים".' },
  { id: 'sen-013', category: 'sentences', subtype: 'contrast-connector', difficulty: 3, approved: true,
    sentence: 'התרופה החדשה ____ את הכאב, אבל לא ____ את המחלה עצמה.',
    options: [['הפחיתה / ריפאה', null], ['הגבירה / ריפאה', 'half-fits'], ['הפחיתה / החמירה', 'ignores-connector'], ['העלימה / גרמה', 'ignores-connector']],
    explain: 'במשפט הזה "אבל" מציב שני דברים זה מול זה: מה שהתרופה כן עשתה, ומה שהיא לא עשתה. היא הפחיתה את הכאב, ומול זה, את המחלה עצמה היא לא ריפאה. בשאר התשובות שני החלקים לא עומדים זה מול זה.' },
  { id: 'sen-014', category: 'sentences', subtype: 'proportion-connector', difficulty: 3, approved: true,
    sentence: 'ככל שהתרחקנו מהמדורה, החום שהרגשנו נעשה ____ יותר, עד שבסוף ____ מקור.',
    options: [['חלש / רעדנו', null], ['חזק / רעדנו', 'half-fits'], ['חלש / הזענו', 'half-fits'], ['נעים / שמחנו', 'ignores-connector']],
    explain: 'הרמז נמצא בסוף המשפט: "מקור". אם בסוף היה קר, סימן שהחום נעשה חלש יותר, ומי שקר לו רועד. "חזק יותר" לא מתאים לסוף שבו קר, ואי אפשר "להזיע מקור" או "לשמוח מקור".' },
  // A knowledge and vocabulary item, kept on purpose: knowing that mountain air is thin is fair game, and there is one clearly best answer.
  { id: 'sen-015', category: 'sentences', subtype: 'vocabulary-knowledge', difficulty: 3, approved: true, vocabulary: ['דליל'],
    sentence: 'ככל שהמטפסים עלו גבוה יותר, האוויר נעשה ____ יותר, והיה להם קשה יותר ____ .',
    options: [['דליל / לנשום', null], ['דליל / לשמוע', 'half-fits'], ['חמים / לנשום', 'half-fits'], ['צבעוני / לטפס', 'ignores-connector']],
    explain: 'בהרים גבוהים האוויר דליל, כלומר יש בו פחות חמצן, ולכן קשה יותר לנשום. גם מי שלא מכיר את המילה "דליל" יכול להיעזר בסוף המשפט: מה שקשה לעשות כשהאוויר משתנה הוא לנשום, ובגובה לא נעשה חם יותר אלא קר יותר.' },
];
